import type { ScanResults } from '../scanner/index.js';
import { writeFileSync } from 'fs';

/**
 * Generate a compact Markdown scan report for PR comments and CI logs.
 */
export function generateMarkdownReport(results: ScanResults, outputPath?: string): string {
  const errorCount = results.summary.bySeverity.error || 0;
  const warningCount = results.summary.bySeverity.warning || 0;
  const infoCount = results.summary.bySeverity.info || 0;
  const status =
    results.summary.totalIssues === 0
      ? '✅ Clean'
      : errorCount > 0
        ? '❌ Issues found'
        : '⚠️ Warnings only';

  const lines: string[] = [];

  lines.push(`## Repro-in-a-Box Scan Report`);
  lines.push('');
  lines.push(`**${status}** · \`${results.url}\``);
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`| --- | --- |`);
  lines.push(`| Pages scanned | ${results.summary.pagesScanned} |`);
  lines.push(`| Total issues | ${results.summary.totalIssues} |`);
  lines.push(`| Errors | ${errorCount} |`);
  lines.push(`| Warnings | ${warningCount} |`);
  lines.push(`| Info | ${infoCount} |`);
  lines.push(`| Duration | ${results.summary.duration} |`);
  lines.push(`| Scanned | ${results.timestamp} |`);
  lines.push('');

  if (results.summary.totalIssues === 0) {
    lines.push('_No issues detected across scanned pages._');
    lines.push('');
  } else {
    if (Object.keys(results.summary.byCategory).length > 0) {
      lines.push('### By category');
      lines.push('');
      for (const [category, count] of Object.entries(results.summary.byCategory)) {
        lines.push(`- **${category}**: ${count}`);
      }
      lines.push('');
    }

    lines.push('### Issues');
    lines.push('');
    lines.push('| Severity | Category | Message | URL |');
    lines.push('| --- | --- | --- | --- |');

    let shown = 0;
    const maxRows = 40;

    for (const page of results.pages) {
      for (const detectorResult of page.detectorResults) {
        for (const issue of detectorResult.issues) {
          if (shown >= maxRows) break;
          const message = escapeMdCell(issue.message);
          const category = escapeMdCell(issue.category);
          const url = escapeMdCell(page.url);
          lines.push(`| ${issue.severity} | ${category} | ${message} | ${url} |`);
          shown++;
        }
        if (shown >= maxRows) break;
      }
      if (shown >= maxRows) break;
    }

    const remaining = results.summary.totalIssues - shown;
    if (remaining > 0) {
      lines.push('');
      lines.push(`_…and ${remaining} more issue${remaining === 1 ? '' : 's'} not shown._`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by [Repro-in-a-Box](https://github.com/forbiddenlink/repro-in-a-box)_');
  lines.push('');

  const markdown = lines.join('\n');
  if (outputPath) {
    writeFileSync(outputPath, markdown, 'utf8');
  }
  return markdown;
}

function escapeMdCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}
