#!/bin/bash
# Reproduction script for https://www.wikipedia.org/
# Generated by Repro-in-a-Box on 2026-02-15T21:35:44.814Z
# 
# This script helps reproduce the detected issues by:
# - Replaying the recorded HAR file (network traffic)
# - Running the same detectors
# - Comparing results

set -e

echo "🔍 Repro-in-a-Box - Reproduction Script"
echo "========================================"
echo ""
echo "Original scan: 2026-02-15T21:35:44.814Z"
echo "Pages scanned: 1"
echo "Issues found: 0"
echo ""

# Check if repro-in-a-box is installed
if ! command -v repro &> /dev/null; then
  echo "❌ repro-in-a-box CLI not found."
  echo ""
  echo "Install it first:"
  echo "  npm install -g repro-in-a-box"
  echo ""
  echo "Or run from the project directory:"
  echo "  npm run dev -- scan https://www.wikipedia.org/"
  exit 1
fi

echo "🚀 Starting reproduction scan..."
echo ""

# Replay with HAR file
repro validate scan-results.json --har recording.har

echo ""
echo "✅ Reproduction complete!"
