import * as fs from 'fs/promises';
import * as path from 'path';
import AdmZip from 'adm-zip';
import type { ScanResults } from '../scanner/index.js';

export interface BundleOptions {
  scanResults: ScanResults;
  outputDir: string;
  outputName?: string;
  harPath?: string;
}

export interface BundleResult {
  bundlePath: string;
  size: number;
  contents: string[];
}

/**
 * Creates a reproducible bundle (ZIP) containing:
 * - Scan results JSON
 * - HAR file (if available)
 * - Screenshots (if available)
 * - Reproduction script
 */
export async function createBundle(options: BundleOptions): Promise<BundleResult> {
  const zip = new AdmZip();
  const contents: string[] = [];

  // 1. Add scan results
  const resultsJson = JSON.stringify(options.scanResults, null, 2);
  zip.addFile('scan-results.json', Buffer.from(resultsJson, 'utf-8'));
  contents.push('scan-results.json');

  // 2. Add HAR file if provided
  if (options.harPath) {
    try {
      const harContent = await fs.readFile(options.harPath);
      const harFilename = path.basename(options.harPath);
      zip.addFile(harFilename, harContent);
      contents.push(harFilename);
    } catch (error) {
      console.warn(`⚠️  HAR file not found: ${options.harPath}`);
    }
  }

  // 3. Add screenshots if any pages have them
  const screenshotPaths = results.pages
    .filter(p => p.screenshotPath)
    .map(p => p.screenshotPath!);
  
  if (screenshotPaths.length > 0) {
    zip.addFile('screenshots/', Buffer.alloc(0)); // Create directory
    
    for (const screenshotPath of screenshotPaths) {
      try {
        const screenshot = await fs.readFile(screenshotPath);
        const filename = path.basename(screenshotPath);
        zip.addFile(`screenshots/${filename}`, screenshot);
        contents.push(`screenshots/${filename}`);
      } catch (error) {
        console.warn(`⚠️  Screenshot not found: ${screenshotPath}`);
      }
    }
  }

  // 4. Generate and add reproduction script
  const reproScript = generateReproductionScript(options.scanResults, !!options.harPath);
  zip.addFile('reproduce.sh', Buffer.from(reproScript, 'utf-8'));
  contents.push('reproduce.sh');

  // 5. Add README
  const readme = generateReadme(options.scanResults);
  zip.addFile('README.md', Buffer.from(readme, 'utf-8'));
  contents.push('README.md');

  // 6. Write bundle to output directory
  await fs.mkdir(options.outputDir, { recursive: true });
  const bundleName = options.outputName || generateBundleName(options.scanResults);
  const bundlePath = path.join(options.outputDir, bundleName);
  
  zip.writeZip(bundlePath);

  const stats = await fs.stat(bundlePath);

  return {
    bundlePath,
    size: stats.size,
    contents,
  };
}

/**
 * Generates shell script for reproducing the scan
 */
function generateReproductionScript(results: ScanResults, hasHar: boolean): string {
  const url = results.pages[0]?.url || 'https://example.com';
  const timestamp = new Date(results.timestamp).toISOString();

  return `#!/bin/bash
# Reproduction script for ${url}
# Generated by Repro-in-a-Box on ${timestamp}
# 
# This script helps reproduce the detected issues by:
# ${hasHar ? '- Replaying the recorded HAR file (network traffic)' : '- Scanning the live site'}
# - Running the same detectors
# - Comparing results

set -e

echo "🔍 Repro-in-a-Box - Reproduction Script"
echo "========================================"
echo ""
echo "Original scan: ${timestamp}"
echo "Pages scanned: ${results.summary.pagesScanned}"
echo "Issues found: ${results.summary.totalIssues}"
echo ""

# Check if repro-in-a-box is installed
if ! command -v repro &> /dev/null; then
  echo "❌ repro-in-a-box CLI not found."
  echo ""
  echo "Install it first:"
  echo "  npm install -g repro-in-a-box"
  echo ""
  echo "Or run from the project directory:"
  echo "  npm run dev -- scan ${url}"
  exit 1
fi

echo "🚀 Starting reproduction scan..."
echo ""

${hasHar ? `# Replay with HAR file
repro validate scan-results.json --har recording.har` : `# Scan live site
repro scan ${url} --max-pages ${results.summary.pagesScanned} --output repro-scan.json

echo ""
echo "📊 Comparing results..."
repro diff scan-results.json repro-scan.json`}

echo ""
echo "✅ Reproduction complete!"
`;
}

/**
 * Generates README for the bundle
 */
function generateReadme(results: ScanResults): string {
  const url = results.pages[0]?.url || 'Unknown';
  const timestamp = new Date(results.timestamp).toISOString();

  // Group issues by severity
  const bySeverity: Record<string, number> = {};
  const byCategory: Record<string, number> = {};

  for (const page of results.pages) {
    for (const [severity, count] of Object.entries(page.summary.bySeverity)) {
      bySeverity[severity] = (bySeverity[severity] || 0) + count;
    }
    for (const [category, count] of Object.entries(page.summary.byCategory)) {
      byCategory[category] = (byCategory[category] || 0) + count;
    }
  }

  return `# Repro-in-a-Box Bundle

## Scan Information

- **URL**: ${url}
- **Timestamp**: ${timestamp}
- **Pages Scanned**: ${results.summary.pagesScanned}
- **Total Issues**: ${results.summary.totalIssues}
- **Duration**: ${results.summary.duration}

## Issues Summary

### By Severity
${Object.entries(bySeverity)
  .sort(([, a], [, b]) => b - a)
  .map(([severity, count]) => `- **${severity}**: ${count}`)
  .join('\n')}

### By Category
${Object.entries(byCategory)
  .sort(([, a], [, b]) => b - a)
  .map(([category, count]) => `- **${category}**: ${count}`)
  .join('\n')}

## Bundle Contents

- \`scan-results.json\` - Complete scan results with all detected issues
- \`reproduce.sh\` - Shell script to reproduce the scan
${results.pages.some(p => p.harPath) ? '- `recording.har` - Network traffic recording for deterministic replay\n' : ''}${results.pages.some(p => p.screenshotPath) ? '- `screenshots/` - Screenshots of pages with issues\n' : ''}- \`README.md\` - This file

## How to Reproduce

1. Extract this bundle
2. Make the reproduction script executable:
   \`\`\`bash
   chmod +x reproduce.sh
   \`\`\`
3. Run the reproduction:
   \`\`\`bash
   ./reproduce.sh
   \`\`\`

## Detailed Issues

See \`scan-results.json\` for complete issue details including:
- Issue messages and descriptions
- Source URLs and line numbers
- Stack traces (where applicable)
- Severity and category classification
`;
}

/**
 * Generates bundle filename based on URL and timestamp
 */
function generateBundleName(results: ScanResults): string {
  const url = results.pages[0]?.url || 'scan';
  const timestamp = new Date(results.timestamp);
  
  // Sanitize URL for filename
  const sanitized = url
    .replace(/^https?:\/\//, '')
    .replace(/[^a-z0-9-]/gi, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 50);

  const dateStr = timestamp.toISOString().split('T')[0]; // YYYY-MM-DD
  const timeStr = timestamp.toTimeString().split(' ')[0].replace(/:/g, '-'); // HH-MM-SS

  return `repro-${sanitized}-${dateStr}-${timeStr}.zip`;
}
